function stressTrans = stressTransformationMatrix(theta)
    stressTrans=[cosd(theta)^2 sind(theta)^2 2*cosd(theta)*sind(theta);...
                sind(theta)^2 cosd(theta)^2 -2*cosd(theta)*sind(theta);...
                -cosd(theta)*sind(theta) cosd(theta)*sind(theta) (cosd(theta)^2)-(sind(theta)^2)];
end